services:
  app:
    build: .
    container_name: freelance-platform
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
